
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cozmina
 */
public class ModificareDate extends javax.swing.JFrame {

    /**
     * Creates new form ModificareDate
     */
    public ModificareDate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        registerUtilizator = new javax.swing.JTextField();
        registerNume = new javax.swing.JTextField();
        registerPrenume = new javax.swing.JTextField();
        registerTara = new javax.swing.JTextField();
        registerTelefon = new javax.swing.JTextField();
        registerEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        registerParola = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        actiuneRegister = new javax.swing.JButton();
        inapoiMeniuIntrare = new javax.swing.JButton();
        registerJudet = new javax.swing.JTextField();
        registerOras = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        registerStrada = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 28, 14));

        jPanel2.setBackground(new java.awt.Color(246, 237, 217));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.PNG"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("MODIFICARE PROFIL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(101, 101, 101)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        registerUtilizator.setBackground(new java.awt.Color(71, 54, 15));
        registerUtilizator.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerUtilizator.setForeground(new java.awt.Color(255, 130, 0));
        registerUtilizator.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerUtilizator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUtilizatorActionPerformed(evt);
            }
        });

        registerNume.setBackground(new java.awt.Color(71, 54, 15));
        registerNume.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerNume.setForeground(new java.awt.Color(255, 130, 0));
        registerNume.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerNume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNumeActionPerformed(evt);
            }
        });

        registerPrenume.setBackground(new java.awt.Color(71, 54, 15));
        registerPrenume.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerPrenume.setForeground(new java.awt.Color(255, 130, 0));
        registerPrenume.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerPrenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPrenumeActionPerformed(evt);
            }
        });

        registerTara.setBackground(new java.awt.Color(71, 54, 15));
        registerTara.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerTara.setForeground(new java.awt.Color(255, 130, 0));
        registerTara.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerTara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerTaraActionPerformed(evt);
            }
        });

        registerTelefon.setBackground(new java.awt.Color(71, 54, 15));
        registerTelefon.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerTelefon.setForeground(new java.awt.Color(255, 130, 0));
        registerTelefon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerTelefonActionPerformed(evt);
            }
        });

        registerEmail.setBackground(new java.awt.Color(71, 54, 15));
        registerEmail.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerEmail.setForeground(new java.awt.Color(255, 130, 0));
        registerEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerEmailActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 130, 0));
        jLabel1.setText("   Utilizator:");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 130, 0));
        jLabel3.setText("   Prenume:");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 130, 0));
        jLabel6.setText("   Tara");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 130, 0));
        jLabel7.setText("   Telefon:");

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 130, 0));
        jLabel8.setText("   Email:");

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 130, 0));
        jLabel9.setText("   Nume:");

        registerParola.setBackground(new java.awt.Color(71, 54, 15));
        registerParola.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerParola.setForeground(new java.awt.Color(255, 130, 0));
        registerParola.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerParola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerParolaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 130, 0));
        jLabel10.setText("   Parola:");

        actiuneRegister.setBackground(new java.awt.Color(204, 134, 87));
        actiuneRegister.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        actiuneRegister.setForeground(new java.awt.Color(102, 51, 0));
        actiuneRegister.setText("Inregistrare");
        actiuneRegister.setFocusable(false);
        actiuneRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actiuneRegisterActionPerformed(evt);
            }
        });

        inapoiMeniuIntrare.setBackground(new java.awt.Color(204, 134, 87));
        inapoiMeniuIntrare.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        inapoiMeniuIntrare.setForeground(new java.awt.Color(102, 51, 0));
        inapoiMeniuIntrare.setText("Inapoi");
        inapoiMeniuIntrare.setFocusable(false);
        inapoiMeniuIntrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inapoiMeniuIntrareActionPerformed(evt);
            }
        });

        registerJudet.setBackground(new java.awt.Color(71, 54, 15));
        registerJudet.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerJudet.setForeground(new java.awt.Color(255, 130, 0));
        registerJudet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerJudet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJudetActionPerformed(evt);
            }
        });

        registerOras.setBackground(new java.awt.Color(71, 54, 15));
        registerOras.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerOras.setForeground(new java.awt.Color(255, 130, 0));
        registerOras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerOras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerOrasActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 130, 0));
        jLabel11.setText("  Judet");

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 130, 0));
        jLabel12.setText("  Oras");

        registerStrada.setBackground(new java.awt.Color(71, 54, 15));
        registerStrada.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        registerStrada.setForeground(new java.awt.Color(255, 130, 0));
        registerStrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        registerStrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerStradaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 130, 0));
        jLabel13.setText("  Strada");

        jLabel14.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 130, 0));
        jLabel14.setText("Pentru a modifica profilul completeaza campurile cu datele noi.");

        jLabel15.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 130, 0));
        jLabel15.setText("Daca doresti ca unele date sa ramana, completeaza campurile cu ");

        jLabel16.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 130, 0));
        jLabel16.setText("cele de la contul original");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addGap(82, 82, 82))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inapoiMeniuIntrare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerUtilizator, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerNume, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerTara, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerParola, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerJudet, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerOras, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerStrada, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(actiuneRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUtilizator, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registerNume, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerParola, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerTara, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerJudet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerOras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerStrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(inapoiMeniuIntrare, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(actiuneRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerUtilizatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUtilizatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerUtilizatorActionPerformed

    private void registerNumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerNumeActionPerformed

    private void registerPrenumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPrenumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerPrenumeActionPerformed

    private void registerTaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerTaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerTaraActionPerformed

    private void registerTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerTelefonActionPerformed

    private void registerEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerEmailActionPerformed

    private void registerParolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerParolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerParolaActionPerformed

    private void actiuneRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actiuneRegisterActionPerformed
        // TODO add your handling code here:
        Utilizator utilizator=new Utilizator( registerUtilizator.getText(), registerParola.getText(), registerNume.getText(), registerPrenume.getText(),registerTelefon.getText(),registerEmail.getText(),registerTara.getText(), registerJudet.getText(),registerOras.getText(),registerStrada.getText(),"0" );
        String id=Integer.toString(Utilizator.cautaUtilizator(Utilizator.selecteazaUsername()));
        if(utilizator.getUtilizator().isEmpty() || utilizator.getParola().isEmpty() || utilizator.getNume().isEmpty() || utilizator.getPrenume().isEmpty() ||  utilizator.getNrTelefon().isEmpty() || utilizator.getEmail().isEmpty()||utilizator.getTara().isEmpty()||utilizator.getJudet().isEmpty()||utilizator.getOras().isEmpty()||utilizator.getStrada().isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Toate campurile trebuie copletate","Eroare",JOptionPane.ERROR_MESSAGE);
        }else if(!Utilizator.isValidUtilizator(utilizator.getUtilizator())){ JOptionPane.showMessageDialog(this, "Numele de utilizator este gresit, trebuie sa aiba minim 3 litere, maxim 15, poate contine daor litere(mari sau mici), cifre, si urmatatoarele caractere speciale . - _ ","Eroare",JOptionPane.ERROR_MESSAGE);}
        else if(!Utilizator.isValidParola(utilizator.getParola())){ JOptionPane.showMessageDialog(this, "Numele de utilizator este gresit, trebuie sa să conțină cel puțin 8 caractere\n să conțină cel puțin o literă mică\n să conțină cel puțin o literă mare\nsă conțină cel puțin un număr\n să conțină cel puțin un caracter special (!, @, #, $, %, ^, &, *, (, ), _, +, -, =)","Eroare",JOptionPane.ERROR_MESSAGE);}
        else if((!Utilizator.isValidNume(utilizator.getNume()))||(!Utilizator.isValidPrenume(utilizator.getPrenume()))){JOptionPane.showMessageDialog(this, "Numele sau prenumele este incorect scris","Eroare",JOptionPane.ERROR_MESSAGE);}
        else if (!Utilizator.isValidEmail(utilizator.getEmail())){      JOptionPane.showMessageDialog(this, "Email Invalid","Eroare",JOptionPane.ERROR_MESSAGE);
        }else if(!Utilizator.isValidPhoneNumber(utilizator.getNrTelefon())){ JOptionPane.showMessageDialog(this, "Nr Telefon Invalid","Eroare",JOptionPane.ERROR_MESSAGE);
        }else if(!Utilizator.isValidTara(utilizator.getTara()))   {JOptionPane.showMessageDialog(this, "Din pacate putem livra doar in Romania momentan, si aceasta este singura tara pe care o acceptam la conturi","Eroare",JOptionPane.ERROR_MESSAGE);}
        else if(!Utilizator.isValidJudet(utilizator.getJudet())){JOptionPane.showMessageDialog(this, "Nume de judet invalid","Eroare",JOptionPane.ERROR_MESSAGE);}
        else if(!Utilizator.isValidOras(utilizator.getOras())){JOptionPane.showMessageDialog(this, "Nume de oras invalid","Eroare",JOptionPane.ERROR_MESSAGE);}        else{   //start the logIn process.
            updateUser(utilizator.getUtilizator(),utilizator.getParola(), utilizator.getNume(), utilizator.getPrenume(), utilizator.getNrTelefon(),utilizator.getEmail(),utilizator.getTara(),utilizator.getJudet(),utilizator.getOras(),utilizator.getStrada(),id);
            emailsend(utilizator.getEmail(),utilizator.getUtilizator(),utilizator.getNume(),utilizator.getPrenume());
           Utilizator utilizator1=new Utilizator(utilizator.getUtilizator(),utilizator.getParola());
           conectareUser(utilizator1);  
            Utilizator.mamConectat(utilizator1);
        }

    }//GEN-LAST:event_actiuneRegisterActionPerformed

    private void inapoiMeniuIntrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inapoiMeniuIntrareActionPerformed
        // TODO add your handling code here:
        dispose();
        MeniuIntrare m=new MeniuIntrare();
        m.setVisible(true);
    }//GEN-LAST:event_inapoiMeniuIntrareActionPerformed

    private void registerJudetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJudetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJudetActionPerformed

    private void registerOrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerOrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerOrasActionPerformed

    private void registerStradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerStradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerStradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificareDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificareDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificareDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificareDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificareDate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actiuneRegister;
    private javax.swing.JButton inapoiMeniuIntrare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField registerEmail;
    private javax.swing.JTextField registerJudet;
    private javax.swing.JTextField registerNume;
    private javax.swing.JTextField registerOras;
    private javax.swing.JTextField registerParola;
    private javax.swing.JTextField registerPrenume;
    private javax.swing.JTextField registerStrada;
    private javax.swing.JTextField registerTara;
    private javax.swing.JTextField registerTelefon;
    private javax.swing.JTextField registerUtilizator;
    // End of variables declaration//GEN-END:variables

private void updateUser(String utilizator, String parola, String nume, String prenume,String nrTelefon, String email,String tara, String judet, String oras, String strada, String lvlpermi) {
        Connection dbconn= ConectareDB.connectDB();
        if(dbconn != null){
        try {
             PreparedStatement st=(PreparedStatement)
             dbconn.prepareStatement("UPDATE users SET utilizator =?, parola = ?, nume = ?,prenume=?,telefon=? , email=?, tara=?, judet=?, oras=?,strada=? WHERE userID= ?");

            st.setString(1, utilizator);
            st.setString(2, parola);
            st.setString(3, nume);
            st.setString(4, prenume);
            st.setString(5, nrTelefon);
            st.setString(6, email);
            st.setString(11,lvlpermi);
            st.setString(7,tara);
            st.setString(8,judet);
            st.setString(9, oras);
            st.setString(10, strada);
            st.executeUpdate();
          
          
                JOptionPane.showMessageDialog(this, "Datele despre utilizator au fost salvate cu succes, veti primi un email de confirmare.","Suces",JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            Logger.getLogger(Conectare.class.getName()).log(Level.SEVERE, null, ex);
        }
    }else
        {
            System.out.println("Conexiunea nu este disponibila.");
        }
        dispose();
    }
    
     public static void emailsend(String mail,String utilizator,String nume, String prenume) {
        // Set system properties
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        // Create a session
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication("cozminascorobete@gmail.com", "iyyj opdl ldrm nufh");
                    }
                });

        try {
            // Create a message
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("cozminascorobete@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(mail));
            message.setSubject("Anima Creare Cont");
            message.setText("Buna ziua "+ nume+ " "+ prenume+", contul dumeanvoastra cu utilizatorul " +utilizator+" a fost updatat cu scucces.");

            // Send the message
            Transport.send(message);
            System.out.println("Email sent successfully.");
        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }
     
       void conectareUser(Utilizator utilizator) {
        Connection dbconn= ConectareDB.connectDB();
        if(dbconn != null){
        try {
            PreparedStatement st=(PreparedStatement)
                    dbconn.prepareStatement("Select * from users WHERE utilizator =? AND parola=?");   
            st.setString(1, utilizator.getUtilizator());
            st.setString(2, utilizator.getParola());
            ResultSet res= st.executeQuery();
            
             
            if(res.next()){
                String perm=res.getString("lvlPermi");
                utilizator.setNume(res.getString("nume"));
                utilizator.setPrenume(res.getString("prenume"));
                utilizator.setEmail(res.getString("email"));
                utilizator.setNrTelefon(res.getString("telefon"));
                utilizator.setTara(res.getString("tara"));
                utilizator.setJudet(res.getString("judet"));
                utilizator.setOras(res.getString("oras"));    
                utilizator.setStrada(res.getString("strada"));    
                utilizator.setNivelPermisiune(res.getString("lvlPermi"));
                //afiseaza meniu nou
                dispose();
                if(perm.equals("0")){
                   MagazinOnline magazin=new MagazinOnline();
                    magazin.setVisible(true);}
                else{InterfataAdmin c=new InterfataAdmin();
                c.setVisible(true);}
                
           
          
                
            }else{
                JOptionPane.showMessageDialog(this, "Utilizatorul/Parola nu au fost gasite","Eroare",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Conectare.class.getName()).log(Level.SEVERE, null, ex);
        }
    }else
        {
            System.out.println("Conexiunea nu este disponibila.");
        }
       }
}


