
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cozmina
 */
public class NrBucati extends javax.swing.JFrame {

    /**
     * Creates new form NrBucati
     */
    public NrBucati() {
        initComponents();
        rezerva.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        schimbaAdresa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nrBucati = new javax.swing.JTextField();
        rezerva = new javax.swing.JButton();
        renunta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 134, 87));

        schimbaAdresa.setBackground(new java.awt.Color(34, 28, 14));
        schimbaAdresa.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        schimbaAdresa.setForeground(new java.awt.Color(255, 130, 0));
        schimbaAdresa.setText("Mai departe");
        schimbaAdresa.setFocusable(false);
        schimbaAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schimbaAdresaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 28, 14));
        jLabel2.setText("Introdu Numarul De Bucati");

        nrBucati.setBackground(new java.awt.Color(71, 54, 15));
        nrBucati.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        nrBucati.setForeground(new java.awt.Color(255, 130, 0));
        nrBucati.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(24, 28, 14), 3, true));
        nrBucati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrBucatiActionPerformed(evt);
            }
        });

        rezerva.setBackground(new java.awt.Color(34, 28, 14));
        rezerva.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        rezerva.setForeground(new java.awt.Color(255, 130, 0));
        rezerva.setText("Rezerva");
        rezerva.setFocusable(false);
        rezerva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rezervaActionPerformed(evt);
            }
        });

        renunta.setBackground(new java.awt.Color(34, 28, 14));
        renunta.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        renunta.setForeground(new java.awt.Color(255, 130, 0));
        renunta.setText("Renunta");
        renunta.setFocusable(false);
        renunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renuntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nrBucati)
                    .addComponent(schimbaAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rezerva, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(renunta, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrBucati, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rezerva)
                    .addComponent(renunta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(schimbaAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schimbaAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schimbaAdresaActionPerformed
        // TODO add your handling code here:
        Produs produs=new Produs();
        produs.setCantitate(Integer.parseInt(nrBucati.getText()));
        Produs temporar=new Produs(Produs.produsTemp());
        Produs baza=new Produs(Produs.cautaProdus(temporar.getId()));
        if(baza.getCantitate()==-9999){JPanel j= new JPanel();
        JOptionPane.showMessageDialog(j, "Ne pare rau dar produsul este indisponibil.","Bucati Insufieciente",JOptionPane.ERROR_MESSAGE);
        dispose();}
        else if(baza.getCantitate()<=0){JPanel j= new JPanel();
        JOptionPane.showMessageDialog(j, "Ne pare rau dar nu mai avem bucati din acest produs momentan, dar il puteti rezerva.","Bucati Insufieciente",JOptionPane.ERROR_MESSAGE);
         rezerva.setVisible(true);}
       else if(Produs.verifNrBuc(baza,produs)){
        Produs.adaugaProdus(temporar);
        Produs.adaugaNrBucati(produs);
        dispose();}else
        {
        JPanel j= new JPanel();
        JOptionPane.showMessageDialog(j, "Ne pare rau dar avem doar, dar puteti rezerva numarul de bucati dorit." +Integer.toString(baza.getCantitate())+" bucati din acest produs","Bucati Insufieciente",JOptionPane.ERROR_MESSAGE);
         rezerva.setVisible(true);
        }
       
    }//GEN-LAST:event_schimbaAdresaActionPerformed

    private void nrBucatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrBucatiActionPerformed
        // TODO add your handling code here:
        
                
    }//GEN-LAST:event_nrBucatiActionPerformed

    private void rezervaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rezervaActionPerformed
        // TODO add your handling code here:
        Produs produs=new Produs();
        produs.setCantitate(Integer.parseInt(nrBucati.getText()));
        Produs temporar=new Produs(Produs.produsTemp());
        Produs baza=new Produs(Produs.cautaProdus(temporar.getId()));
        Produs.adaugaProdusR(temporar);
        Produs.adaugaNrBucatiR(produs);
        dispose();
    }//GEN-LAST:event_rezervaActionPerformed

    private void renuntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renuntaActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_renuntaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NrBucati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NrBucati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NrBucati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NrBucati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NrBucati().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nrBucati;
    private javax.swing.JButton renunta;
    private javax.swing.JButton rezerva;
    private javax.swing.JButton schimbaAdresa;
    // End of variables declaration//GEN-END:variables
}
