
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Cozmina
 */
public class VizualizareRezervare extends javax.swing.JFrame {

    /**
     * Creates new form VizualizareRezervare
     */
    public VizualizareRezervare() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        inapoiMeniuIntrare = new javax.swing.JButton();
        pasulUrmator = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cosLista = new javax.swing.JTextArea();
        pasulUrmator1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 28, 14));

        jPanel3.setBackground(new java.awt.Color(246, 237, 217));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.PNG"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("REZERVARI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(149, 149, 149)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        inapoiMeniuIntrare.setBackground(new java.awt.Color(204, 134, 87));
        inapoiMeniuIntrare.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        inapoiMeniuIntrare.setForeground(new java.awt.Color(102, 51, 0));
        inapoiMeniuIntrare.setText("Inapoi");
        inapoiMeniuIntrare.setFocusable(false);
        inapoiMeniuIntrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inapoiMeniuIntrareActionPerformed(evt);
            }
        });

        pasulUrmator.setBackground(new java.awt.Color(204, 134, 87));
        pasulUrmator.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        pasulUrmator.setForeground(new java.awt.Color(102, 51, 0));
        pasulUrmator.setText("Apasa pentru a vizualiza Factura");
        pasulUrmator.setFocusable(false);
        pasulUrmator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasulUrmatorActionPerformed(evt);
            }
        });

        cosLista.setBackground(new java.awt.Color(34, 28, 14));
        cosLista.setColumns(20);
        cosLista.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        cosLista.setForeground(new java.awt.Color(255, 130, 0));
        cosLista.setRows(5);
        cosLista.setBorder(null);
        cosLista.setFocusable(false);
        cosLista.setSelectionColor(new java.awt.Color(0, 153, 51));
        jScrollPane1.setViewportView(cosLista);

        pasulUrmator1.setBackground(new java.awt.Color(204, 134, 87));
        pasulUrmator1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        pasulUrmator1.setForeground(new java.awt.Color(102, 51, 0));
        pasulUrmator1.setText("Apasa pentru a vizualiza datele de facuturare");
        pasulUrmator1.setFocusable(false);
        pasulUrmator1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasulUrmator1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pasulUrmator1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(inapoiMeniuIntrare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(pasulUrmator, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasulUrmator, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inapoiMeniuIntrare, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(pasulUrmator1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inapoiMeniuIntrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inapoiMeniuIntrareActionPerformed
        // TODO add your handling code here:
        dispose();
        MagazinOnline m= new MagazinOnline();
        m.setVisible(true);

    }//GEN-LAST:event_inapoiMeniuIntrareActionPerformed

    private void pasulUrmatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasulUrmatorActionPerformed
        // TODO add your handling code here:
        try (BufferedReader reader = new BufferedReader(new FileReader("rezervare.txt"))) {
            String line;
            int lineNr=0;
            StringBuilder name = new StringBuilder("Hi");

            Produs produsFisier=new Produs( );
            Produs produsBaza=new Produs();
            while ((line = reader.readLine()) != null) {
                lineNr++;
                if(lineNr>3){
                    lineNr=1;}
                if(lineNr==1){
                    produsBaza= new Produs( Produs.cautaProdus(Integer.parseInt(line)));
                    name.delete(0,name.length());
                    name.append(Produs.cautaNume(Integer.parseInt(line)));
                    // System.out.println(Integer.toString(lineNr)+name+line);
                }
                else if(lineNr==2){}
                else if(lineNr==3){
                    produsFisier=new Produs( produsBaza,line);
                    produsFisier.setNume(produsBaza.getNume());
                    afisareCos(produsFisier, produsFisier.getCantitate(),name);
                    adaugaFacutra(produsFisier, produsFisier.getCantitate(),name);
                   // Produs.updateNrBuc(produsBaza,produsFisier);
                    //  System.out.println(name);
                }
                //  System.out.println(line);
                // System.out.println(lineNr);
                //  Produs produsFisier=new Produs( produsBaza,buc);
                //  Produs.updateNrBuc(produsBaza,produsFisier);

            } afisareTotal();
            totalFacutura();

        } catch (IOException e) {
        }
        ///////////////////////////////////////
        // Comanda.emailsend();
    }//GEN-LAST:event_pasulUrmatorActionPerformed

    private void pasulUrmator1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasulUrmator1ActionPerformed
        // TODO add your handling code here:
        dispose();
        DateFacturaRezervare d= new DateFacturaRezervare();
        d.setVisible(true);
    }//GEN-LAST:event_pasulUrmator1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VizualizareRezervare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VizualizareRezervare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VizualizareRezervare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VizualizareRezervare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VizualizareRezervare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cosLista;
    private javax.swing.JButton inapoiMeniuIntrare;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pasulUrmator;
    private javax.swing.JButton pasulUrmator1;
    // End of variables declaration//GEN-END:variables

  public void afisareCos(Produs produs, int buc, StringBuilder s){
    int pret=produs.getPret()*buc;
    cosLista.append("\n"+s.toString()+"    Nr Bucati: "+Integer.toString(buc)+" Pret: "+Integer.toString(pret)+"\n");
    cosLista.append("_______________________________________");    
    }

  
    public void afisareTotal(){
    int pret=Produs.sumaCosR();
    cosLista.append("\n Suma totala de plata:                                           "+Integer.toString(pret));
       
    }
    
    public static void adaugaFacutra(Produs produs, int buc, StringBuilder s){
   int pret=produs.getPret()*buc;
         try{
     BufferedWriter writer= new BufferedWriter(new FileWriter("facturaR.txt", true)) ;  
            writer.write("\n"+s.toString()+"    Nr Bucati: "+Integer.toString(buc)+" Pret: "+Integer.toString(pret)+"\n");
            writer.write("_______________________________________");
            writer.close();
          
    }catch(IOException e){}
     System.out.println("produs adaugat cu succes la facutra");
      }
    public void totalFacutura(){
    int pret=Produs.sumaCos();
         try{
     BufferedWriter writer= new BufferedWriter(new FileWriter("facturaR.txt", true)) ;  
            writer.write("\n Suma totala de plata:                                           "+Integer.toString(pret));
           
            writer.close();
          
    }catch(IOException e){}
     System.out.println("total adaugat cu succes la facutra");
    }
}
